import Head from 'next/head'
import { ReactElement } from 'react'

import styles from '@app/styles/Home.module.css'

type Props = {
  children?: ReactElement
}

export const Layout = ({ children }: Props) => (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>{children}</main>
  </div>
)
